package com.garfield.wechatorder.dal.domain;

public class DivisionDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column division.id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column division.code
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column division.name
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column division.level
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column division.parent_code
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private String parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column division.created_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column division.updated_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column division.is_deleted
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column division.id
     *
     * @return the value of division.id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column division.id
     *
     * @param id the value for division.id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column division.code
     *
     * @return the value of division.code
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column division.code
     *
     * @param code the value for division.code
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column division.name
     *
     * @return the value of division.name
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column division.name
     *
     * @param name the value for division.name
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column division.level
     *
     * @return the value of division.level
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column division.level
     *
     * @param level the value for division.level
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column division.parent_code
     *
     * @return the value of division.parent_code
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column division.parent_code
     *
     * @param parentCode the value for division.parent_code
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column division.created_at
     *
     * @return the value of division.created_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column division.created_at
     *
     * @param createdAt the value for division.created_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column division.updated_at
     *
     * @return the value of division.updated_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column division.updated_at
     *
     * @param updatedAt the value for division.updated_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column division.is_deleted
     *
     * @return the value of division.is_deleted
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column division.is_deleted
     *
     * @param isDeleted the value for division.is_deleted
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}