package com.garfield.wechatorder.dal.domain;

public class MateNoteDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mate_note.id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mate_note.user_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mate_note.title
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mate_note.content
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mate_note.place
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mate_note.start_time
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mate_note.end_time
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mate_note.phone
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mate_note.created_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mate_note.updated_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mate_note.is_deleted
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mate_note.id
     *
     * @return the value of mate_note.id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mate_note.id
     *
     * @param id the value for mate_note.id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mate_note.user_id
     *
     * @return the value of mate_note.user_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mate_note.user_id
     *
     * @param userId the value for mate_note.user_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mate_note.title
     *
     * @return the value of mate_note.title
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mate_note.title
     *
     * @param title the value for mate_note.title
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mate_note.content
     *
     * @return the value of mate_note.content
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mate_note.content
     *
     * @param content the value for mate_note.content
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mate_note.place
     *
     * @return the value of mate_note.place
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mate_note.place
     *
     * @param place the value for mate_note.place
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mate_note.start_time
     *
     * @return the value of mate_note.start_time
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mate_note.start_time
     *
     * @param startTime the value for mate_note.start_time
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mate_note.end_time
     *
     * @return the value of mate_note.end_time
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mate_note.end_time
     *
     * @param endTime the value for mate_note.end_time
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mate_note.phone
     *
     * @return the value of mate_note.phone
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mate_note.phone
     *
     * @param phone the value for mate_note.phone
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mate_note.created_at
     *
     * @return the value of mate_note.created_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mate_note.created_at
     *
     * @param createdAt the value for mate_note.created_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mate_note.updated_at
     *
     * @return the value of mate_note.updated_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mate_note.updated_at
     *
     * @param updatedAt the value for mate_note.updated_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mate_note.is_deleted
     *
     * @return the value of mate_note.is_deleted
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mate_note.is_deleted
     *
     * @param isDeleted the value for mate_note.is_deleted
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}