package com.garfield.wechatorder.dal.domain;

public class NoteDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.title
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.user_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.content
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.created_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.updated_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.is_deleted
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.id
     *
     * @return the value of note.id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.id
     *
     * @param id the value for note.id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.title
     *
     * @return the value of note.title
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.title
     *
     * @param title the value for note.title
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.user_id
     *
     * @return the value of note.user_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.user_id
     *
     * @param userId the value for note.user_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.content
     *
     * @return the value of note.content
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.content
     *
     * @param content the value for note.content
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.created_at
     *
     * @return the value of note.created_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.created_at
     *
     * @param createdAt the value for note.created_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.updated_at
     *
     * @return the value of note.updated_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.updated_at
     *
     * @param updatedAt the value for note.updated_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.is_deleted
     *
     * @return the value of note.is_deleted
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.is_deleted
     *
     * @param isDeleted the value for note.is_deleted
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}