package com.garfield.wechatorder.dal.domain;

public class NoteCommentDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_comment.id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_comment.note_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long noteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_comment.user_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_comment.comment
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_comment.created_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_comment.updated_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_comment.is_deleted
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_comment.id
     *
     * @return the value of note_comment.id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_comment.id
     *
     * @param id the value for note_comment.id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_comment.note_id
     *
     * @return the value of note_comment.note_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getNoteId() {
        return noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_comment.note_id
     *
     * @param noteId the value for note_comment.note_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setNoteId(Long noteId) {
        this.noteId = noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_comment.user_id
     *
     * @return the value of note_comment.user_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_comment.user_id
     *
     * @param userId the value for note_comment.user_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_comment.comment
     *
     * @return the value of note_comment.comment
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_comment.comment
     *
     * @param comment the value for note_comment.comment
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_comment.created_at
     *
     * @return the value of note_comment.created_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_comment.created_at
     *
     * @param createdAt the value for note_comment.created_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_comment.updated_at
     *
     * @return the value of note_comment.updated_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_comment.updated_at
     *
     * @param updatedAt the value for note_comment.updated_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_comment.is_deleted
     *
     * @return the value of note_comment.is_deleted
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_comment.is_deleted
     *
     * @param isDeleted the value for note_comment.is_deleted
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}