package com.garfield.wechatorder.dal.domain;

public class UserFollowDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_follow.id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_follow.user_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_follow.follow_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long followId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_follow.created_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_follow.updated_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Long updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_follow.is_deleted
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_follow.id
     *
     * @return the value of user_follow.id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_follow.id
     *
     * @param id the value for user_follow.id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_follow.user_id
     *
     * @return the value of user_follow.user_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_follow.user_id
     *
     * @param userId the value for user_follow.user_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_follow.follow_id
     *
     * @return the value of user_follow.follow_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getFollowId() {
        return followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_follow.follow_id
     *
     * @param followId the value for user_follow.follow_id
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setFollowId(Long followId) {
        this.followId = followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_follow.created_at
     *
     * @return the value of user_follow.created_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_follow.created_at
     *
     * @param createdAt the value for user_follow.created_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_follow.updated_at
     *
     * @return the value of user_follow.updated_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_follow.updated_at
     *
     * @param updatedAt the value for user_follow.updated_at
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_follow.is_deleted
     *
     * @return the value of user_follow.is_deleted
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_follow.is_deleted
     *
     * @param isDeleted the value for user_follow.is_deleted
     *
     * @mbg.generated Mon Aug 20 15:30:30 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}