server:
  port: 9001
app:
  id: speech
knowledge:
  init:
    knowledgeTitles:
      - kdTitle: 听不清
        keyWords: "[你说什么，没听清，听不清楚，再说一遍]"
        question: "[没听懂，听不清楚]"
      - kdTitle: 无应答
        kdInfos:
          - 你好
          - hello
          - hi

